pipeline{
    agent any
    stages{
        stage("build in progress"){
            steps{
              echo "building in progress "
              sh "cat index.html"
            }
        }
        stage("deploy"){
            steps{
                echo "deploying "
               
            }
        }
        
     
        
    }
   
    
    
}